#  Copyright (c) Brockmann Consult GmbH, 2024
#  License: MIT
name: fcwq
channels:
  - conda-forge
dependencies:
  - python = 3.10.8
  #
  # Imports
  - cartopy
  - dask
  - dask-image
  - matplotlib
  - xarray
  - xbatcher = 0.4.0
  - xcube
  - xgboost = 2.1.3
  # runtime
  - h5netcdf
  - netcdf4
  - zarr
  #
  # Extra
  - jupyterlab = 4.2.5
  - nbstripout
  - seaborn
  #
  # Test
  - pytest
  - pytest-cov
  #
  # Lint
  - black
  - black-jupyter
  - flake8
